### PR TITLE
change call to decidim ludens path

### LINKED ISSUE #57: Ludens cannot find participative actions file and causes internal server error
#### Description

For instance in production mode Decidim Ludens cannot find correctly the participative actions yaml file. 

See [participative_action model](https://github.com/OpenSourcePolitics/decidim-ludens/blob/cfa8f36cf6e320b63cf94e7764c4484783ee2f34/app/models/decidim/ludens/participative_action.rb#L24)

#### Version 

* Module ludens : release/0.26-stable

#### Stacktrace

```
{"method":"GET","path":"/admin/","format":"html","controller":"Decidim::Admin::DashboardController","action":"show","status":500,"error":"ActionView::Template::Error: No such file or directory - bundle","duration":142.71,"view":0.0,"db":46.34,"remote_ip":"xxxxxx","params":{},"user_id":1,"organization_id":1,"referer":"https://xxxxxx/admin/organization/edit"}

 ActionView::Template::Error (No such file or directory - bundle):
   2:   <div class="assistant_values grid-y">
   3:     <div class="grid-x assistant_container">
    4:       <h3 class="assistant_level letter_spaced">
    5:         <%= t "decidim.admin.assistant.level", level: participative_actions_level(current_user) %>
   6:       </h3>
    7:       <input type=hidden
    8:              name="level_up_message"
 decidim-ludens (cfa8f36cf6e3) app/models/decidim/ludens/participative_action.rb:24:in ``'
 decidim-ludens (cfa8f36cf6e3) app/models/decidim/ludens/participative_action.rb:24:in `actions_file'
 decidim-ludens (cfa8f36cf6e3) app/models/decidim/ludens/participative_action.rb:29:in `actions'
 decidim-ludens (cfa8f36cf6e3) app/overrides/concerns/user_extends.rb:16:in `participative_actions_level'
 decidim-ludens (cfa8f36cf6e3) app/helpers/decidim/ludens/ludens_helper.rb:15:in `participative_actions_level'
 decidim-ludens (cfa8f36cf6e3) app/views/decidim/admin/dashboard/_recap_assistant.html.erb:5
 actionview (6.0.6.1) lib/action_view/base.rb:274:in `_run'
 actionview (6.0.6.1) lib/action_view/template.rb:185:in `block in render'
 activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `block in instrument'
```

### Alternative solutions

Add in `decidim-app` the participative actions yaml file 

`bundle exec rake decidim_ludens:get_file`

### PR DESCRIPTION
**Pull request by eliegaboriau**
#### Description

Load Participative actions YAML file based on gemspec full gem path 

#### Fixes

Fixes #57

### CODE REVIEW

File: app/models/decidim/ludens/participative_action.rb [hunk 1]
```diff
@@ -21,7 +21,7 @@ def self.actions_file
         @actions_file ||= if File.exist?(Rails.root.join("config/participative_actions.yaml"))
                             YAML.safe_load(File.read(Rails.root.join("config/participative_actions.yaml")))
                           else
-                            YAML.safe_load(File.read("#{`bundle info decidim-ludens --path`.strip}/config/participative_actions.yaml"))
+                            YAML.safe_load(File.read(decidim_ludens_path.join("config/participative_actions.yaml")))
```
Comment (Quentinchampenois) [inline app/models/decidim/ludens/participative_action.rb]: `decidim_ludens_path` can be nil here, it can causes crash when call `join()` on Nil Object

**Review by Quentinchampenois — CHANGES_REQUESTED** [review]
Hello, I have a change request to prevent crash 

Also I will attempt to load this branch on a decidim-app to ensure it works as expected

**Review by armandfardeau — APPROVED** [review]

**Review by Quentinchampenois — APPROVED** [review]

**Review by paulinebessoles — APPROVED** [review]
